name: wormsdev
channels:
 # - schrodinger
 - conda-forge
 - numba
dependencies:
 - python == 3.5.5
 - numpy
 - numba
# - icc_rt
 - pandas
 - pytest
 - pytest-cov
 - sphinx_rtd_theme
 - ipython
 - toolz
 - cffi
 # - pymol >= 2.1
 - pip:
   - homog >= 0.1.10
   - xbin >= 0.1.5
   - hypothesis
   - pytest-sugar
   - pytest-xdist
   - tqdm
   - git+https://github.com/willsheffler/rif.git@devel
