name: worms
channels:
 - schrodinger
 - conda-forge
 - numba
 - asford
dependencies:
 - pyrosetta
 - python >= 3.6
 - numpy
 - numba
 - icc_rt
 - pandas
 - pytest
 - pytest-faulthandler
 - sphinx_rtd_theme
 - ipython
 - toolz
 - cffi
 - pymol >= 2.1
 - pip:
   - homog >= 0.1.10
   - xbin >= 0.1.5
   - hypothesis
   - pytest-sugar
   - pytest-xdist
   - tqdm

