name: wormsdev
channels:
 - schrodinger
 - conda-forge
dependencies:
 - python >= 3.6
 - numpy
 - pytest
 - pytest-cov
 - sphinx_rtd_theme
 - ipython
 - pymol >= 2.1
 - pip:
   - homog >= 0.1.10
   - hypothesis
   - pytest-sugar
   - pytest-xdist
   - tqdm
